server:
  port: 8080
  servlet:
    context-path: ${app.api.context-path:/api}

spring:
  application:
    name: file-share-platform
  
  # 数据库配置
  datasource:
    url: jdbc:h2:mem:fileshare
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # H2控制台配置
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  
  # 错误处理配置
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/
  
  # 错误页面配置
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always

# 自定义配置
app:
  api:
    context-path: /api

file:
  upload:
    path: ./uploads
    max-size: 104857600  # 100MB
    allowed-types: .jpg,.jpeg,.png,.gif,.pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.txt,.zip,.rar,.7z,.mp4,.avi,.mov
  cleanup:
    interval: 3600000  # 1小时检查一次 (毫秒)
    retention-hours: 24  # 文件保留24小时

# 日志配置
logging:
  level:
    cn.lemwood: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Actuator配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always