database:
  default:
    type: sqlite
    url: jdbc:sqlite:./data/external-config-test.db
    driver-class-name: org.sqlite.JDBC
  
  development:
    type: sqlite
    url: jdbc:sqlite:./data/fileshare_dev.db
    driver-class-name: org.sqlite.JDBC
  
  test:
    type: sqlite
    url: jdbc:sqlite:./data/fileshare_test.db
    driver-class-name: org.sqlite.JDBC
  
  production:
    type: sqlite
    url: jdbc:sqlite:./data/fileshare_prod.db
    driver-class-name: org.sqlite.JDBC
  
  development-mysql:
    type: mysql
    url: jdbc:mysql://localhost:3306/fileshare_dev?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  
  test-mysql:
    type: mysql
    url: jdbc:mysql://localhost:3306/fileshare_test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  
  production-mysql:
    type: mysql
    url: jdbc:mysql://localhost:3306/fileshare_prod?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password